name: helm-chartsnap-action
description: GitHub action to do continuous snapshot testing for Helm chart in your CI
author: jlandowner

branding:
  color: blue
  icon: anchor

inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}

  chart:
    description: Name of the Helm chart in remote repository or local chart directory path
    required: true

  repo:
    description: URL of the remote Helm repository
    required: false

  values:
    description: Path to the values file or directory
    required: false

  additional_args:
    description: Addtional args for the command "helm template" (e.g. --namespace kube-system, --skip-tests, --show-only etc.)
    required: false

  update_snapshot:
    description: If set true, update snapshot and create pull request if snapshots are changed
    required: false

  disable_create_pull_request:
    description: If set true, disable to create pull request even if snapshots are changed
    required: false

runs:
  using: composite
  steps:
    - id: setup-helm
      uses: azure/setup-helm@v4

    - id: setup-chartsnap
      run: |
        helm plugin install https://github.com/jlandowner/helm-chartsnap || helm plugin update chartsnap
      shell: bash

    - id: run-chartsnap
      run: |
        [[ ! -z $VALUES ]] && OPT_VALUES="-f $VALUES"
        [[ ! -z $UPDATE_SNAPSHOT ]] && OPT_UPDATE_SNAPSHOT="-u"
        [[ ! -z $REPO ]] && OPT_REPO="--repo $REPO"
        [[ ! -z $ADDTIONAL_ARGS ]] && OPT_ADDTIONAL_ARGS=$ADDTIONAL_ARGS
        [[ ! -z $REPO ]] || [[ ! -z $ADDTIONAL_ARGS ]] && OPT_ARGS_SEP="-- "
        CMD="helm chartsnap -c $CHART $OPT_VALUES $OPT_UPDATE_SNAPSHOT $OPT_ARGS_SEP $OPT_REPO $OPT_ADDTIONAL_ARGS"
        echo $CMD; eval $CMD
      env:
        CHART:  ${{ inputs.chart }}
        REPO:   ${{ inputs.repo }}
        VALUES: ${{ inputs.values }}
        ADDTIONAL_ARGS: ${{ inputs.additional_args }}
        UPDATE_SNAPSHOT: ${{ inputs.update_snapshot }}
      shell: bash

    - name: Create Pull Request
      id: cpr
      if: ${{ inputs.update_snapshot && !inputs.disable_create_pull_request }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.token }}
        commit-message: Update snapshot by helm chartsnap action
        author: GitHub <noreply@github.com>
        branch: helm-chartsnap-action
        title: Update helm chart snapshot ${{ inputs.chart }}
        labels: snapshot
        branch-suffix: random
        delete-branch: true
        body: |
          Update snapshot by helm-chartsnap-action 🤖

            CHART:  ${{ inputs.chart }}
            REPO:   ${{ inputs.repo }}
            VALUES: ${{ inputs.values }}

    - name: Close Duplicated Pull Requests
      if: steps.cpr.outcome == 'success'
      run: |
        SEARCH_VALUE="Update snapshot by helm-chartsnap-action 🤖 CHART: ${{ inputs.chart }} REPO: ${{ inputs.repo }} VALUES: ${{ inputs.values }}"
        PR_NUMBERS=$(gh pr list --state open --search "$SEARCH_VALUE" --json number | jq -r '.[].number')
        for PR_NUMBER in $PR_NUMBERS; do
          if [[ $PR_NUMBER != $CREATED_PR_NUMBER ]]; then
            gh pr close $PR_NUMBER --comment "Auto-closing pull request" --delete-branch
          fi
        done
      env:
        GH_TOKEN: ${{ inputs.token }}
        CREATED_PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
      shell: bash

    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      shell: bash
